- src/genImage.jsx
Currently not working, but this is likely due to an API problem. Prodia providers not affected.
> Add Pixart and PixartLCM image providers

- CHANGELOG.md
- package-lock.json
- package.json
- src/aiChat.jsx
- src/api/gpt.jsx
Add back Google Gemini as an alternative *might* be preferred by users.
However the clear drawback is it has an API Key, which complicates the preferences as well as causes potential confusion (if the API Key doesn't work, etc.)
To think more about this and consider whether the additional option is worth the added complexity.
> Add Google Gemini

- src/aiChat.jsx
- src/api/gpt.jsx
Currently only useful for the `Bing` provider.
Uses the code given by the g4f-ts package.
> Add streaming support

- package-lock.json
- package.json
- src/aiChat.jsx
- src/api/gpt.jsx
- src/api/meta_llama3.jsx
This should not work permanently though, apparently Replicate has a 'free trial period' of unspecified length before you need to enter a credit card.
> Add Meta Llama 3, by Replicate provider

- package.json
- src/aiChat.jsx
- src/api/deepinfra_llama3.jsx
- src/api/gpt.jsx
- src/api/replicate_llama3.jsx
implementation ported from gpt4free: https://github.com/xtekky/gpt4free/blob/main/g4f/Provider/DeepInfra.py
Fully working with streaming support.
> Add DeepInfra provider (Llama3_8B and Llama3_70B)

- .github/workflows/code_quality.yml
Now we install all necessary dependencies so correct context is used during the checks.
> Improve Qodana checks

- src/aiChat.jsx
- src/api/Providers/replicate.jsx
- src/api/gpt.jsx
- src/api/helper.jsx
* Code reorganisation
* Fix for Blackbox provider
* Fix for Bing provider
> Assorted changes & bug fixes

- package.json
- src/aiChat.jsx
- src/api/Providers/replicate.jsx
- src/api/gpt.jsx
There are now two llama-3 models, 8B and 70B.
> Update Replicate provider

- src/aiChat.jsx
This replaces the simple "Copy Chat Transcript" feature we had previously.
> Add Import/Export Chat feature

- src/aiChat.jsx
- src/api/gpt.jsx
Shortcut: cmd+shift+opt+/
Works both in AI Chat and useGPT.
Also contains a few bug fixes.
> Add "Stop Response" feature

- src/aiChat.jsx
- src/api/Providers/deepinfra.jsx
- src/api/Providers/google_gemini.jsx
- src/api/Providers/replicate.jsx
- src/api/gpt.jsx
Very similar to the corresponding Raycast AI feature.
**NOTE: This is NOT recognized by all providers. Currently only DeepInfra, Replicate and Google Gemini use this setting.**
Also includes a couple of related minor refactors.
> Add Creativity settings in AI Chat

- src/aiChat.jsx
- src/api/gpt.jsx
1) providers has been renamed to providers_info. It's now a dictionary of objects with provider, model and stream properties.
2) some minor updates to usage of providers_info
> Refactor providers info

- src/aiChat.jsx
- src/genImage.jsx
AI Chat:
"Copy Response" added, copies the raw text of the selected message
"Delete Last Message" changed to "Delete Message" which now deletes the selected message.
Generate Images:
"Show in Finder" now shows the selected image
"Copy Image Path" added, copies the path of the selected image
"Delete Last Image" changed to "Delete Image" which now deletes the selected image.
> Improve actions in AI Chat and Generate Images

- package.json
- src/api/customCommands.jsx
- src/api/gpt.jsx
- src/customAICommands.jsx
The new "Custom AI Commands" command allows for adding, editing, removing and running AI Commands, similar to Raycast AI.
> Custom AI Commands

- package.json
- src/aiChat.jsx
- src/api/gpt.jsx
- src/helpers/update.jsx
**Experimental feature.**
Automatically check for updates at a **maximum** interval of once per day. Additionally, the check only triggers when a command is called (i.e. an AI command is used, or a message is sent in AI Chat).
> Automatically Check for Updates

- src/aiChat.jsx
- src/api/Providers/blackbox.jsx
- src/api/Providers/deepinfra.jsx
- src/api/Providers/ecosia.jsx
- src/api/Providers/g4f.jsx
- src/api/Providers/google_gemini.jsx
- src/api/Providers/nexra.jsx
- src/api/Providers/replicate.jsx
- src/api/gpt.jsx
- src/classes/message.jsx
- src/helpers/helper.jsx
Improve a large portion of AI Chat code by introducing dedicated classes `Message` and `MessagePair`, which is basically just a wrapper around the same things we were using before.
This makes the code more readable; it also paves the way for future features like file/image upload.
For maximum backwards compatibility, the parameter names are all the same as before. Additionally both new classes are completely JSON-compatible and can completely be used as a primitive object just like before.
Also includes many related code refactors and QoL improvements.
> Rewrite code: Introduce Message & MessagePair class

- README.md
- package.json
- src/api/gpt.jsx
- src/api/providers.jsx
- src/askAI.jsx
- src/askAboutScreenContent.jsx
- src/helpers/update.jsx
Also includes some cleanups in package.json.
> Add "Ask About Screen Content" command

- package.json
- src/aiChat.jsx
You can now pin chats in AI Chat by selecting "Pin Chat" in the actions. This will:
- Display the chat in a separate "Pinned" section in the chats dropdown;
- Prevent the chat from being purged If the auto-delete chats feature is enabled.
To unpin a pinned chat, just select "Pin Chat" again.
> Pin Chat functionality in AI Chat

- src/genImage.jsx
Images are now displayed in a List view, consistent with the style used in AI Chat.
The "Regenerate Image" option has been added.
The storage-related code has been modernized to align with the rest of the extension.
Code refactor.
> Revamp "Generate Images"

- src/genImage.jsx
- src/helpers/helpPage.jsx
Also add its own help page, where the list of available models is documented.
> Allow model selection in "Generate Images"

- package-lock.json
- package.json
- src/api/gpt.jsx
- Fix screenshots being uploaded multiple times in "Ask About Screen Content" if response is regenerated
- Update gemini-g4f to fix issue with .mov file uploads
> Bug fixes for file uploads

- package.json
- src/aiChat.jsx
- src/api/Providers/deepinfra.jsx
- src/api/Providers/g4f_local.jsx
- src/api/storage.jsx
- src/api/tools/code.jsx
- src/api/tools/web.jsx
- src/askAboutScreenContent.jsx
- src/genImage.jsx
- src/helpers/helper.jsx
- src/helpers/update.jsx
Adds the experimental Code Interpreter feature. It allows GPT to execute Python code locally. The model has been instructed to strictly only produce safe and responsible code, but use at your own risk!
Only models with function calling capabilities will support this feature. As of now, this includes only selected DeepInfra models.
Also updates the list of models that support function calling.
> Add Code Interpreter feature

- README.md
- package.json
- src/aiChat.jsx
- src/api/Providers/deprecated/ecosia.jsx
- src/api/gpt.jsx
- src/api/providers.jsx
Cloudflare detection...
It is moved to the Deprecated directory and no longer used.
> Remove Ecosia provider

- src/aiChat.jsx
- src/api/gpt.jsx
- src/configureLocalAPIs.jsx
- src/genImage.jsx
Allow the user to edit chat settings after chat creation. Note that the system prompt is not updated because they are handled during initialization of chats.
Also, change all toast messages to the same capitalization scheme: first letter uppercase only.
> Add "Edit Chat Settings" action in AI Chat, change Toast messages

- README.md
- package.json
- src/api/Providers/deepinfra.jsx
- src/api/providers.jsx
This model is capable of understanding images, similar to Gemini. Simply upload files and chat with it!
The code has been updated to allow for image inputs.
> Add llava-1.5-7b model (hosted by DeepInfra)

- src/api/Providers/ollama_local.jsx
- src/configureLocalAPIs.jsx
Added options to change the API URL and context size.
> Add more Ollama config settings

- Privacy.md
- README.md
- package.json
- src/api/Providers/sambanova.jsx
- src/api/gpt.jsx
- src/api/providers.jsx
This provider offers EXTREMELY fast generation of llama3-405b, 70b and 8b models.
One small downside is the relatively small context window (4K on 405b, unknown for other models).
> Add SambaNova provider

- src/aiChat.jsx
- src/api/storage.jsx
- src/helpers/helper.jsx
The AI Chat module was completely rewritten. We now only load chats from storage when they are needed. This saves a significant amount of memory and improves performance, especially with a large number of conversations.
known changes (NOT BUGS)
- response will not fully update if you switch to another chat before the response completes.
> [v3.0-alpha.1] Major AI Chat rewrite

- src/aiChat.jsx
- src/api/storage.jsx
- src/customAICommands.jsx
- src/genImage.jsx
- src/helpers/helper.jsx
- src/manageAIPresets.jsx
The AI Chat command was completely rewritten. We now only load chats from storage when they are needed. This saves a significant amount of memory and improves performance, and this increased efficiency should be noticeable especially with a large number of conversations.
> Major AI Chat rewrite

- src/aiChat.jsx
There's a type error when writing lastPruneChatsTime from local to file storage
> Fix lastPruneChatsTime serialization

- src/aiChat.jsx
- src/api/providers.jsx
- src/helpers/helper.jsx
With a single shortcut, this will create a chat with the default name, provider and settings.
closes #98
> Add "Quickly Create Chat" action in AI Chat

- README.md
- package-lock.json
- package.json
- src/api/Providers/deepinfra.jsx
- src/api/tools/web.jsx
DuckDuckGo search is not only much faster and comprehensive, but it also removes the need for any API Key.
The duck-duck-scrape package is used to make requests to DuckDuckGo.
> Use DuckDuckGo for web search

- .github/workflows/npm_build.yml
- README.md
- assets/scripts/update.sh
- src/helpers/update.jsx
Thanks to issue #113 for reporting this - see more [here](https://github.com/XInTheDark/raycast-g4f/issues/113#issuecomment-2396857632).
We now use `npm run dev` everywhere to build the extension, since `npm run build` apparently doesn't update the extension fully.
> Fix automatic updates

- package.json
- src/format.jsx
LLMs are unbelievably good at formatting text - so here it is!
> Add Format Text command

- package-lock.json
- package.json
- src/aiChat.jsx
- src/api/gpt.jsx
This is a major bug fix.
Previously, out-of-memory issues would sometimes be encountered during response generation; this occurred especially for longer responses.
This issue was caused by the lack of throttling in the updates to the chat data; the frequent renders apparently prevented the garbage collector from functioning properly.
This patch throttles the updates at 100ms intervals, both in AI Chat and in commands. We use lodash.throttle, a lightweight and functional library. The memory usage issue has since been fixed, as verified through comparisons of memory usage logs.
This patch also fixes a bug where Web Search would be called twice in AI Chat.
Additionally, a Developer Mode option has been added to the preferences. When enabled, it automatically logs memory usage.
> Fix memory usage in AI Chat

- src/api/Providers/bestim.js
- src/api/Providers/blackbox.js
- src/api/Providers/chatgptfree.js
- src/api/Providers/phind.js
- src/api/curl.js
Remove the need for a cb function; we now return an async generator.
Also fixed ChatgptFree provider.
> Simplify curl interface

- package-lock.json
- package.json
- src/genImage.jsx
Fixed the Nexra provider. They had changed their API.
Also added the **Flux** and **Midjourney** models.
fixes #94, fixes #117
> Fix image generation, add new image models

- src/api/curl.js
- src/api/shell.js
- src/api/tools/ddgs.js
- src/askAboutScreenContent.jsx
- src/helpers/customCommands.jsx
Find the documentation in https://github.com/XInTheDark/raycast-g4f/wiki/Help-page:-Dynamic-Placeholders
> Support shell commands in Dynamic Placeholders

- src/customAICommands.jsx
- src/helpers/customCommands.jsx
- src/helpers/helper.js
- Allow setting a keyboard shortcut
- Optimisations
> Improve Custom AI Commands

- src/api/Providers/blackbox.js
- src/api/Providers/dev/blackbox/blackbox_engineer.js
... in addition to the more lightweight puppeteer-core
> Add support for puppeteer module

- src/aiChat.jsx
- src/api/gpt.jsx
- src/helpers/throttle.js
The support for dynamic throttling is now implemented in a separate module. It can be reused across various parts of the extension.
Also, we now dynamically throttle the following: View Response action in AI Chat; All AI commands.
> Add throttle helper module
