package.json
src/aiChat.jsx
src/api/Providers/blackbox.jsx
src/api/Providers/replicate.jsx
src/api/gpt.jsx

Fully working. Comes with web search capabilities, which is toggled using the `webSearchMode: true` field in `data`. However this is by default set to true, and currently not possible to disable, because the main advantage of Blackbox is the web search function anyways.

Add Blackbox provider

---

package.json
src/aiChat.jsx

Automatically delete inactive chats after a set interval (in preferences).
This is done by calling the pruneChats function every time an AI chat generation completes. But it only performs the search every 30 minutes (defined by pruneChatsInterval), so performance impact is very minimal.

Add "Prune Inactive Chats" feature

---

package.json
src/aiChat.jsx
src/api/Providers/deepinfra.jsx
src/api/Providers/replicate.jsx
src/api/gpt.jsx
src/api/web.jsx

Adds basic Web Search capability that can be enabled in Preferences. **Currently only available in AI Chat**, will consider implementing into other AI commands later. Currently more testing of this feature needs to be done.
Summary: When the user sends a message, the AI decides for itself whether to run a web search. The [system prompt](https://github.com/XInTheDark/raycast-g4f/blob/web_search/src/api/web.jsx) is used to instruct the AI that it should request a web search only when it is strongly relevant to the user query.
Searches are done using the [Tavily API](https://docs.tavily.com/docs/tavily-api/introduction); an API Key needs to be provided in Preferences, and for the free plan there is a limit of 1000 requests/month.
Also included: many many refactors.
closes #19

Add Web Search capabilities

---

package.json
src/aiChat.jsx
src/api/gpt.jsx
src/api/helper.jsx

Add Smart Chat Naming functionality, similar to ChatGPT web UI. After the user's 1st (or 2nd) message, the AI automatically generates a concise name for the conversation.
Implementation details:
1. refactored chat data so that each chat now has an unique ID (based on creation time). This is to support multiple chats potentially having the same name.
2. moved a couple of functions into helper.jsx
3. also corrected the isShowingDetail logic so the empty chat screen for empty chats is now the same when Web Search is enabled.
Lightly tested.

Add "Smart Chat Naming" functionality

---

package.json
src/aiChat.jsx
src/api/Providers/blackbox.jsx
src/api/Providers/deepinfra.jsx
src/api/Providers/nexra.jsx
src/api/Providers/replicate.jsx
src/api/gpt.jsx
src/api/helper.jsx
src/api/web.jsx

The new implementation uses the Nexra ChatGPT v2 API.
Because streaming is a pretty useful feature, this also changes the default provider to gpt-3.5-turbo.
Also includes:
- fix updateCurrentChat using name instead of id
- tweak web search prompt
- remove redundant "duplicate name" check in create chat
- update processChunks function to yield full response instead of incrementally

Change gpt-3.5-turbo API to support streaming

---

package.json
src/aiChat.jsx
src/api/web.jsx

- better system prompt
- tweaks to web search wrapper
- I  have set the "search_depth" parameter in the Tavily API to "advanced" which yields better search results, but at the cost of using 2 requests. The current "solution" is to allow pasting of multiple Tavily API Keys in preferences, so that we can fallback one by one in case the rate limit is reached.

Improvements to Web Search

---

package-lock.json
package.json
src/aiChat.jsx
src/api/Providers/google_gemini.jsx
src/api/gpt.jsx

The removal of Gemini was probably not the best idea... >:)
1. Google API Keys are completely free and the rate limits are pretty generous: https://ai.google.dev/gemini-api/docs/models/gemini
2. Gemini models (specifically gemini-1.5-flash) are pretty good
Part of the reason why Gemini was removed is because I didn't write streaming support for it, and that made it pretty subpar. But now I have also added **streaming support** for it!! To make this possible, I refactored a sizable chunk of code. There is some added complexity, but hopefully it's organised well enough. I've also tried my best to ensure that nothing should break when it comes to backward compatibility.
We now also support multiple Gemini API Keys in the preferences, so the rate limit is effectively increased.

Add Google Gemini provider back

---

package-lock.json
package.json
src/api/Providers/blackbox.jsx
src/api/Providers/deepinfra.jsx
src/api/Providers/ecosia.jsx
src/api/Providers/google_gemini.jsx
src/api/Providers/nexra.jsx
src/api/Providers/replicate.jsx
src/api/web.jsx

Migrate everything to node-fetch instead of node-fetch-polyfill.
Following this change we can also now update gemini-ai to v2.1.0

Migrate to node-fetch, update gemini-ai to v2

---

README.md
src/aiChat.jsx
src/api/gpt.jsx
src/api/helpPage.jsx
src/customAICommands.jsx

This is accessed via the `Help` action. 
They just link to the GitHub wiki pages on this repository.

Add help pages for commands

---

src/aiChat.jsx
src/api/customCommands.jsx
src/api/gpt.jsx
src/api/storage.jsx
src/genImage.jsx
src/helpers/update.jsx

Adds the new combined read() and write() functions while still keeping support for LocalStorage and File storage APIs respectively. When reading, first read from local storage as usual, but if the data is not found, then fallback to file storage. Similarly, when writing, we write to local storage as usual, but sync the data from local storage to file storage once every 5 minutes (maximum).
TLDR: This commit allows for data to be saved persistently even after local storage is cleared.
Detailed documentation in storage.jsx.
Also includes:
- change all occurrences of `new Date().getTime()` to `Date.now()`

Add Storage interface for persistent storage

---

src/aiChat.jsx
src/api/gpt.jsx

For unknown reasons, the useEffect hook in gpt.jsx is rendered twice, both at the same time.
This results in getResponse() being called twice whenever a command is called directly (i.e. the form is not shown).
This problem has always been present, and it's also present in the original raycast-gemini.
The problem is reproducible by launching any AI command **with all arguments passed directly from the root search**. The displayed text will switch back and forth between two different generating responses. The problem is especially noticeable when using a provider that streams chunks quickly. 
We work around this by preventing any generation when the generationStatus.loading flag is set to true.

Fix double response generation in AI commands

---

src/api/customCommands.jsx
src/api/gpt.jsx
src/customAICommands.jsx
src/translate.jsx

Full list found here: https://github.com/XInTheDark/raycast-g4f/wiki/Help-page:-Dynamic-Placeholders
Technical details:
- The processPrompt parameter is now always run with `await`. This is supposed to make no difference for non-async functions, and this is verified with the Translate function.

Add more Dynamic Placeholders

---

README.md
package.json
src/api/storage.jsx

Add Persistent Storage preference

---

Privacy.md
README.md
package.json
src/api/Providers/g4f.jsx
src/api/Providers/nexra.jsx
src/api/gpt.jsx
src/api/providers.jsx

Removed the inactive Bing provider.
Removed the dependency when generating text completions for `gpt-4-32k` model. We now call the Nexra API endpoint directly.
This means that we only use g4f-ts for image generation now.

First step to removing g4f-ts package

---

README.md
package-lock.json
package.json
src/api/Providers/google_gemini.jsx
src/api/providers.jsx

We try to use gemini-1.5-pro first, and if we are rate limited, we switch to gemini-1.5-flash.
Gemini-1.5-pro is an even more capable model than its faster counterpart.
See https://github.com/XInTheDark/gemini-ai/commit/9b50785b42d23eb94f7ce2e8c0f32db79b5fba2f.

Automatic model detection for Google Gemini

---

src/api/gpt.jsx

The dot (.) does not match newlines by default, so .* failed to match content that spans multiple lines.

Fix Blackbox formatting

---

README.md
src/api/Providers/nexra.jsx
src/api/Providers/phind.jsx
src/api/Providers/replicate.jsx
src/classes/message.jsx

For providers that don't natively support file uploads, we try to read the file as text, then add it directly as a message.

Allow file uploads for all providers

---

README.md
package.json
src/aiChat.jsx
src/api/Providers/deepinfra.jsx
src/api/gpt.jsx
src/api/tools/web.jsx
src/askAI.jsx
src/askAboutSelectedText.jsx
src/customAICommands.jsx
src/explain.jsx
src/helpers/presets.jsx
src/manageAIPresets.jsx

This patch rewrites the Web Search feature by introducing four options: Disabled ("off"), Automatic ("auto"), Balanced ("balanced") and Always ("always").
The intended behaviour is as follows:
- If "off", then a web search will never be made.
- If "auto", the web search is only available in AI Chat. The model will choose whether to make web searches. (This is the same behaviour as before.)
- If "balanced", then in AI Chat we will set web search mode to "auto", while in AI commands we always search.
- If "always", a web search will always be made, both in AI Chat and (some) AI commands.
*Note: Only some AI commands will support web search, since in others (e.g. Summarize, Paraphrase) it makes little sense to search.*
Additionally, in AI Chat, the user can now choose individual web search …

Rewrite Web Search feature

---

src/aiChat.jsx
src/api/gpt.jsx
src/format.jsx
src/helpers/markdown.jsx

In certain contexts, we want to render as plain text - e.g. the Format Text command.
The Detail view only supports markdown currently, so we perform modifications on the markdown to render it as plain text. It's not a perfect implementation, but most of the time it works correctly.
This feature has been added to:
- a new "View as Plain Text" command in AI Chat
- Format Text command

Support rendering as plain text

---

README.md
package.json
src/api/gpt.jsx

Show a cursor icon when the response is loading - cosmetic option only.
The emoji used is a filled circle (●), similar to what was previously used in ChatGPT.

Add cursor icon during response loading

---

package.json
src/askAboutBrowserTab.jsx
src/helpers/browser.jsx
src/helpers/customCommands.jsx

- Added the "Ask About Browser Tab" command (disabled by default).
- Added the {browser-tab} dynamic placeholder.
Tested to be working on Brave.
fixes #138

Add Browser Extension support

---

src/aiChat.jsx

The ordering of chats is now consistent. Previously, when pinning a chat, the chats dropdown would update to order the pinned chat at the top, but the actual internal order in chatData.chats would stay the same. This causes the "Next Chat" and "Previous Chat" actions to behave inconsistently.
Now, the internal order is updated, so that it's the exact same as displayed in the chats dropdown.
Additionally, a large optimisation: we memoize the chats dropdown so it's only updated when the chats array actually changes. (The current selected chat is still passed correctly to the dropdown because it's not memoized; similarly, the dropdown is not re-rendered when currentChat changes.) 
This is very large because the dropdown used to unnecessarily re-render upon typing anything in the search bar.

Improve chats order + large optimisation in AI Chat

---

README.md
package-lock.json
package.json
requirements.txt
src/api/tools/ddgs.js
src/api/tools/web.jsx
src/helpers/env.js
src/helpers/helper.js

duck-duck-scrape is unmaintained and doesn't work anymore.
We use the duckduckgo-search Python package instead. It is added to requirements.txt as an optional dependency.

Fix DuckDuckGo web search

---

package.json
src/aiChat.jsx
src/api/Providers/blackbox.js
src/api/gpt.jsx
src/helpers/helper.js

formatResponse is no longer called in the generation function itself. Instead, it is used by the provider. It makes the generation code less messy.
This also makes the responses consistent between what the provider generates, and what is actually displayed.
Lastly, this is a large performance optimisation since formatResponse is now called only when necessary, instead of being called after every chunk.

Optimise response formatting

---

README.md
package-lock.json
package.json
src/api/Providers/google_gemini.js
src/api/fetch.js

gemini-g4f is now unmaintained. gemini-ai-sdk is the better, simpler way to use Gemini AI, also maintained by me. It's been rewritten from scratch, and it's so much simpler. More features coming soon.
New dependencies: gemini-ai-sdk, undici (for polyfill, since Raycast doesn't support native fetch yet.)
Removed dependency: gemini-g4f

Switch to gemini-ai-sdk package for Google Gemini

---

src/aiChat.jsx
src/api/Providers/blackbox.js
src/api/gpt.jsx
src/helpers/helper.js

The Paste action now overrides the behavior for Cmd+V. 
It uses the Raycast API to fetch the text and file (if any) from the Clipboard, then updates the input accordingly.
This is available in the Compose Message action in AI Chat, as well as in the Form views of all AI Commands.

Add Paste action to AI Chat and AI Commands
